about:
  - alt: Vinyl
    animation:
      animate:
        rotate: 360
      transition:
        duration: 20
        ease: linear
        repeat: Infinity
    position:
      left: 10px
      top: 10px
      type: absolute
    size:
      height: 4
      width: 4
    src: /vinyl.svg
    zIndex: 10
  - alt: CD
    animation:
      animate:
        rotate: -360
      transition:
        duration: 15
        ease: linear
        repeat: Infinity
    position:
      right: 20px
      top: 20px
      type: absolute
    size:
      height: 3
      width: 3
    src: /cd.svg
    zIndex: 10
  - alt: Radio
    animation:
      animate:
        "y":
          - 0
          - -10
          - 0
      transition:
        duration: 2
        ease: easeInOut
        repeat: Infinity
    position:
      bottom: 10px
      left: 60%
      type: absolute
    size:
      height: 5
      width: 5
    src: /radio.svg
    zIndex: 11
hero:
  - alt: Guitar
    animation:
      animate:
        rotate:
          - -10
          - 10
          - -10
        "y":
          - -10
          - 10
          - -10
      transition:
        duration: 4
        ease: easeInOut
        repeat: Infinity
    position:
      left: 10%
      top: 80%
      type: absolute
    size:
      height: 9
      width: 9
    src: /guitar_10.svg
    zIndex: 10
  - alt: Drum
    animation:
      animate:
        rotate:
          - -5
          - 5
          - -5
        scale:
          - 1
          - 1.1
          - 1
      transition:
        duration: 3
        ease: easeInOut
        repeat: Infinity
    position:
      left: 90%
      right: 15%
      top: 30%
      type: absolute
    size:
      height: 5
      width: 5
    src: /drum_9.svg
    zIndex: 10
quiz:
  - alt: Guitar
    animation:
      animate:
        rotate:
          - -5
          - 5
          - -5
      transition:
        duration: 4
        ease: easeInOut
        repeat: Infinity
    position:
      left: 5%
      top: 20px
      type: absolute
    size:
      height: 5
      width: 5
    src: /guitar_4.svg
    zIndex: 10
  - alt: Drum
    animation:
      animate:
        scale:
          - 1
          - 1.1
          - 1
      transition:
        duration: 2
        ease: easeInOut
        repeat: Infinity
    position:
      right: 5%
      top: 40px
      type: absolute
    size:
      height: 4
      width: 4
    src: /drum_9.svg
    zIndex: 10
  - alt: Tambourine
    animation:
      animate:
        rotate:
          - 0
          - 360
      transition:
        duration: 10
        ease: linear
        repeat: Infinity
    position:
      bottom: 20px
      left: 10%
      type: absolute
    size:
      height: 3
      width: 3
    src: /tambourine.svg
    zIndex: 10
  - alt: Piano
    animation:
      animate:
        "y":
          - -5
          - 5
          - -5
      transition:
        duration: 3
        ease: easeInOut
        repeat: Infinity
    position:
      bottom: 40px
      right: 10%
      type: absolute
    size:
      height: 5
      width: 5
    src: /piano.svg
    zIndex: 10
